version: '3.2'

services:
    backend:
        build: ./backend
        ports:
            - 5000:5000
        depends_on:
            - training
        volumes:
            - model:/src/model
    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        container_name: frontend
    training:
        build: ./training
        volumes: 
            - images:/src/imgs
            - model:/src/model
volumes:
    images:
    model: